/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company extends org.jooq.impl.TableImpl<com.jooqtest.model.tables.records.CompanyRecord> {

	private static final long serialVersionUID = -318316373;

	/**
	 * The singleton instance of <code>jooqtest.company</code>
	 */
	public static final com.jooqtest.model.tables.Company COMPANY = new com.jooqtest.model.tables.Company();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooqtest.model.tables.records.CompanyRecord> getRecordType() {
		return com.jooqtest.model.tables.records.CompanyRecord.class;
	}

	/**
	 * The column <code>jooqtest.company.id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.CompanyRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooqtest.company.name</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.CompanyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>jooqtest.company.email</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.CompanyRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>jooqtest.company.city</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.CompanyRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>jooqtest.company</code> table reference
	 */
	public Company() {
		this("company", null);
	}

	/**
	 * Create an aliased <code>jooqtest.company</code> table reference
	 */
	public Company(java.lang.String alias) {
		this(alias, com.jooqtest.model.tables.Company.COMPANY);
	}

	private Company(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.CompanyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Company(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.CompanyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooqtest.model.Jooqtest.JOOQTEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.jooqtest.model.tables.records.CompanyRecord, java.lang.Long> getIdentity() {
		return com.jooqtest.model.Keys.IDENTITY_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jooqtest.model.tables.records.CompanyRecord> getPrimaryKey() {
		return com.jooqtest.model.Keys.KEY_COMPANY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jooqtest.model.tables.records.CompanyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jooqtest.model.tables.records.CompanyRecord>>asList(com.jooqtest.model.Keys.KEY_COMPANY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooqtest.model.tables.Company as(java.lang.String alias) {
		return new com.jooqtest.model.tables.Company(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooqtest.model.tables.Company rename(java.lang.String name) {
		return new com.jooqtest.model.tables.Company(name, null);
	}
}
