/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Driver extends org.jooq.impl.TableImpl<com.jooqtest.model.tables.records.DriverRecord> {

	private static final long serialVersionUID = -696080798;

	/**
	 * The singleton instance of <code>jooqtest.driver</code>
	 */
	public static final com.jooqtest.model.tables.Driver DRIVER = new com.jooqtest.model.tables.Driver();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooqtest.model.tables.records.DriverRecord> getRecordType() {
		return com.jooqtest.model.tables.records.DriverRecord.class;
	}

	/**
	 * The column <code>jooqtest.driver.id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooqtest.driver.first_name</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>jooqtest.driver.last_name</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>jooqtest.driver.birthday</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>jooqtest.driver.telephone</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>jooqtest.driver.car_id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooqtest.driver.company_id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>jooqtest.driver</code> table reference
	 */
	public Driver() {
		this("driver", null);
	}

	/**
	 * Create an aliased <code>jooqtest.driver</code> table reference
	 */
	public Driver(java.lang.String alias) {
		this(alias, com.jooqtest.model.tables.Driver.DRIVER);
	}

	private Driver(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.DriverRecord> aliased) {
		this(alias, aliased, null);
	}

	private Driver(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.DriverRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooqtest.model.Jooqtest.JOOQTEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> getIdentity() {
		return com.jooqtest.model.Keys.IDENTITY_DRIVER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jooqtest.model.tables.records.DriverRecord> getPrimaryKey() {
		return com.jooqtest.model.Keys.KEY_DRIVER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jooqtest.model.tables.records.DriverRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jooqtest.model.tables.records.DriverRecord>>asList(com.jooqtest.model.Keys.KEY_DRIVER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, ?>>asList(com.jooqtest.model.Keys.DRIVER_IBFK_1, com.jooqtest.model.Keys.DRIVER_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooqtest.model.tables.Driver as(java.lang.String alias) {
		return new com.jooqtest.model.tables.Driver(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooqtest.model.tables.Driver rename(java.lang.String name) {
		return new com.jooqtest.model.tables.Driver(name, null);
	}
}
