/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>jooqtest</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.jooqtest.model.tables.records.CarRecord, java.lang.Long> IDENTITY_CAR = Identities0.IDENTITY_CAR;
	public static final org.jooq.Identity<com.jooqtest.model.tables.records.CompanyRecord, java.lang.Long> IDENTITY_COMPANY = Identities0.IDENTITY_COMPANY;
	public static final org.jooq.Identity<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> IDENTITY_DRIVER = Identities0.IDENTITY_DRIVER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.CarRecord> KEY_CAR_PRIMARY = UniqueKeys0.KEY_CAR_PRIMARY;
	public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.CompanyRecord> KEY_COMPANY_PRIMARY = UniqueKeys0.KEY_COMPANY_PRIMARY;
	public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.DriverRecord> KEY_DRIVER_PRIMARY = UniqueKeys0.KEY_DRIVER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, com.jooqtest.model.tables.records.CarRecord> DRIVER_IBFK_1 = ForeignKeys0.DRIVER_IBFK_1;
	public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, com.jooqtest.model.tables.records.CompanyRecord> DRIVER_IBFK_2 = ForeignKeys0.DRIVER_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.jooqtest.model.tables.records.CarRecord, java.lang.Long> IDENTITY_CAR = createIdentity(com.jooqtest.model.tables.Car.CAR, com.jooqtest.model.tables.Car.CAR.ID);
		public static org.jooq.Identity<com.jooqtest.model.tables.records.CompanyRecord, java.lang.Long> IDENTITY_COMPANY = createIdentity(com.jooqtest.model.tables.Company.COMPANY, com.jooqtest.model.tables.Company.COMPANY.ID);
		public static org.jooq.Identity<com.jooqtest.model.tables.records.DriverRecord, java.lang.Long> IDENTITY_DRIVER = createIdentity(com.jooqtest.model.tables.Driver.DRIVER, com.jooqtest.model.tables.Driver.DRIVER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.CarRecord> KEY_CAR_PRIMARY = createUniqueKey(com.jooqtest.model.tables.Car.CAR, com.jooqtest.model.tables.Car.CAR.ID);
		public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.CompanyRecord> KEY_COMPANY_PRIMARY = createUniqueKey(com.jooqtest.model.tables.Company.COMPANY, com.jooqtest.model.tables.Company.COMPANY.ID);
		public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.DriverRecord> KEY_DRIVER_PRIMARY = createUniqueKey(com.jooqtest.model.tables.Driver.DRIVER, com.jooqtest.model.tables.Driver.DRIVER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, com.jooqtest.model.tables.records.CarRecord> DRIVER_IBFK_1 = createForeignKey(com.jooqtest.model.Keys.KEY_CAR_PRIMARY, com.jooqtest.model.tables.Driver.DRIVER, com.jooqtest.model.tables.Driver.DRIVER.CAR_ID);
		public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DriverRecord, com.jooqtest.model.tables.records.CompanyRecord> DRIVER_IBFK_2 = createForeignKey(com.jooqtest.model.Keys.KEY_COMPANY_PRIMARY, com.jooqtest.model.tables.Driver.DRIVER, com.jooqtest.model.tables.Driver.DRIVER.COMPANY_ID);
	}
}
