/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in jooqtest
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooqtest.car
	 */
	public static final com.jooqtest.model.tables.Car CAR = com.jooqtest.model.tables.Car.CAR;

	/**
	 * The table jooqtest.company
	 */
	public static final com.jooqtest.model.tables.Company COMPANY = com.jooqtest.model.tables.Company.COMPANY;

	/**
	 * The table jooqtest.driver
	 */
	public static final com.jooqtest.model.tables.Driver DRIVER = com.jooqtest.model.tables.Driver.DRIVER;
}
