/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarRecord extends org.jooq.impl.UpdatableRecordImpl<com.jooqtest.model.tables.records.CarRecord> implements org.jooq.Record7<java.lang.Long, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = -378189414;

	/**
	 * Setter for <code>jooqtest.car.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooqtest.car.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>jooqtest.car.manufactor</code>.
	 */
	public void setManufactor(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooqtest.car.manufactor</code>.
	 */
	public java.lang.String getManufactor() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jooqtest.car.create_date</code>.
	 */
	public void setCreateDate(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooqtest.car.create_date</code>.
	 */
	public java.sql.Date getCreateDate() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>jooqtest.car.model</code>.
	 */
	public void setModel(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jooqtest.car.model</code>.
	 */
	public java.lang.String getModel() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>jooqtest.car.color</code>.
	 */
	public void setColor(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jooqtest.car.color</code>.
	 */
	public java.lang.String getColor() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>jooqtest.car.door_quantity</code>.
	 */
	public void setDoorQuantity(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jooqtest.car.door_quantity</code>.
	 */
	public java.lang.Integer getDoorQuantity() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>jooqtest.car.patrol</code>.
	 */
	public void setPatrol(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jooqtest.car.patrol</code>.
	 */
	public java.lang.Byte getPatrol() {
		return (java.lang.Byte) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.sql.Date, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.jooqtest.model.tables.Car.CAR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.jooqtest.model.tables.Car.CAR.MANUFACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return com.jooqtest.model.tables.Car.CAR.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.jooqtest.model.tables.Car.CAR.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.jooqtest.model.tables.Car.CAR.COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.jooqtest.model.tables.Car.CAR.DOOR_QUANTITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return com.jooqtest.model.tables.Car.CAR.PATROL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getManufactor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getDoorQuantity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getPatrol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value2(java.lang.String value) {
		setManufactor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value3(java.sql.Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value4(java.lang.String value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value5(java.lang.String value) {
		setColor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value6(java.lang.Integer value) {
		setDoorQuantity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord value7(java.lang.Byte value) {
		setPatrol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarRecord values(java.lang.Long value1, java.lang.String value2, java.sql.Date value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.Byte value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CarRecord
	 */
	public CarRecord() {
		super(com.jooqtest.model.tables.Car.CAR);
	}

	/**
	 * Create a detached, initialised CarRecord
	 */
	public CarRecord(java.lang.Long id, java.lang.String manufactor, java.sql.Date createDate, java.lang.String model, java.lang.String color, java.lang.Integer doorQuantity, java.lang.Byte patrol) {
		super(com.jooqtest.model.tables.Car.CAR);

		setValue(0, id);
		setValue(1, manufactor);
		setValue(2, createDate);
		setValue(3, model);
		setValue(4, color);
		setValue(5, doorQuantity);
		setValue(6, patrol);
	}
}
